"""customer subscription table

Revision ID: c41bd605362c
Revises: 17acbf8ed39d
Create Date: 2026-07-06 20:41:11.271098+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'c41bd605362c'
down_revision: Union[str, None] = '17acbf8ed39d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_subscriptions',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('plan_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('inactive', 'active', 'past_due', 'cancelled', name='subscription_status_enum'), server_default='inactive', nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_billing_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('items_used_in_current_period', sa.Integer(), nullable=False),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_customer_subs_billing_worker', 'customer_subscriptions', ['status', 'next_billing_date'], unique=False)
    op.create_index('ix_customer_subs_business_status', 'customer_subscriptions', ['business_id', 'status'], unique=False)
    op.create_index('ix_customer_subs_customer_id', 'customer_subscriptions', ['customer_id'], unique=False)
    op.add_column('orders', sa.Column('customer_id', sa.UUID(), nullable=True))
    op.add_column('orders', sa.Column('subscription_id', sa.UUID(), nullable=True))
    op.create_index('ix_orders_subscription_id', 'orders', ['subscription_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'users', ['customer_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'orders', 'customer_subscriptions', ['subscription_id'], ['id'], ondelete='SET NULL')
    op.add_column('transactions', sa.Column('subscription_id', sa.UUID(), nullable=True))
    op.create_index('ix_transactions_subscription_id', 'transactions', ['subscription_id'], unique=False)
    op.create_foreign_key(None, 'transactions', 'customer_subscriptions', ['subscription_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index('ix_transactions_subscription_id', table_name='transactions')
    op.drop_column('transactions', 'subscription_id')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index('ix_orders_subscription_id', table_name='orders')
    op.drop_column('orders', 'subscription_id')
    op.drop_column('orders', 'customer_id')
    op.drop_index('ix_customer_subs_customer_id', table_name='customer_subscriptions')
    op.drop_index('ix_customer_subs_business_status', table_name='customer_subscriptions')
    op.drop_index('ix_customer_subs_billing_worker', table_name='customer_subscriptions')
    op.drop_table('customer_subscriptions')
    # ### end Alembic commands ###
