"""tokenized_card_table

Revision ID: 5a1c74d617ba
Revises: 5cf6aa6412c9
Create Date: 2026-07-06 23:03:27.085451+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '5a1c74d617ba'
down_revision: Union[str, None] = '5cf6aa6412c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
