"""token_card_table

Revision ID: 5cf6aa6412c9
Revises: c41bd605362c
Create Date: 2026-07-06 23:01:04.283378+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '5cf6aa6412c9'
down_revision: Union[str, None] = 'c41bd605362c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokenized_cards',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=False),
    sa.Column('token_key', sa.String(length=128), nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['customer_subscriptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tokenized_cards_account_active', 'tokenized_cards', ['account_id', 'is_active'], unique=False)
    op.create_index('ix_tokenized_cards_email', 'tokenized_cards', ['customer_email'], unique=False)
    op.create_index('ix_tokenized_cards_user_active', 'tokenized_cards', ['user_id', 'is_active'], unique=False)
    op.create_index('uq_tokenized_cards_token_key', 'tokenized_cards', ['token_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_tokenized_cards_token_key', table_name='tokenized_cards')
    op.drop_index('ix_tokenized_cards_user_active', table_name='tokenized_cards')
    op.drop_index('ix_tokenized_cards_email', table_name='tokenized_cards')
    op.drop_index('ix_tokenized_cards_account_active', table_name='tokenized_cards')
    op.drop_table('tokenized_cards')
    # ### end Alembic commands ###
