"""add account name to business_subaccounts table

Revision ID: 17acbf8ed39d
Revises: 331cbd758356
Create Date: 2026-07-06 10:14:22.675374+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '17acbf8ed39d'
down_revision: Union[str, None] = '331cbd758356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_subaccounts', sa.Column('virtual_account_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_subaccounts', 'virtual_account_name')
    # ### end Alembic commands ###
