"""profile_image_to_users

Revision ID: 46ad6508b672
Revises: 5a1c74d617ba
Create Date: 2026-07-07 12:06:58.043575+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46ad6508b672'
down_revision: Union[str, None] = '5a1c74d617ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'current_kyb_status')
    op.add_column('users', sa.Column('profile_picture_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_picture_url')
    op.add_column('businesses', sa.Column('current_kyb_status', postgresql.ENUM('pending', 'verified', 'rejected', 'expired', name='verification_status_enum'), server_default=sa.text("'pending'::verification_status_enum"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
