"""create business kyc and kyb tables

Revision ID: 53935bda36b5
Revises: 2e05ecf9457d
Create Date: 2026-07-02 19:21:30.265416+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from geoalchemy2 import Geography
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53935bda36b5'
down_revision: Union[str, None] = '2e05ecf9457d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=60), nullable=True),
    sa.Column('state', sa.String(length=60), nullable=True),
    sa.Column('cac_registration_number', sa.String(length=255), nullable=True),
    sa.Column('business_premises_photos', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('location', Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_discoverable', sa.Boolean(), nullable=False),
    sa.Column('current_kyb_status', postgresql.ENUM('pending', 'verified', 'rejected', 'expired', name='verification_status_enum'), server_default='pending', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    #op.create_index('idx_businesses_location', 'businesses', ['location'], unique=False, postgresql_using='gist')
    op.create_index('ix_business_name', 'businesses', ['name'], unique=False)
    op.create_index('ix_businesses_owner_user_id', 'businesses', ['owner_user_id'], unique=True)
    op.create_table('kyc_verifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id_type', sa.String(length=50), nullable=False),
    sa.Column('id_number', sa.String(length=255), nullable=False),
    sa.Column('document_url', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('provider_reference', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kyc_id_type', 'kyc_verifications', ['id_type'], unique=False)
    op.create_index('idx_kyc_user', 'kyc_verifications', ['user_id'], unique=False)
    op.create_table('kyb_verifications',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('id_type', sa.String(length=50), nullable=False),
    sa.Column('id_number', sa.String(length=255), nullable=False),
    sa.Column('document_url', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('provider_reference', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kyb_business', 'kyb_verifications', ['business_id'], unique=False)
    op.create_index('idx_kyb_id_type', 'kyb_verifications', ['id_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_kyb_id_type', table_name='kyb_verifications')
    op.drop_index('idx_kyb_business', table_name='kyb_verifications')
    op.drop_table('kyb_verifications')
    op.drop_index('idx_kyc_user', table_name='kyc_verifications')
    op.drop_index('idx_kyc_id_type', table_name='kyc_verifications')
    op.drop_table('kyc_verifications')
    op.drop_index('ix_businesses_owner_user_id', table_name='businesses')
    op.drop_index('ix_business_name', table_name='businesses')
    # op.drop_index('idx_businesses_location', table_name='businesses', postgresql_using='gist')
    op.drop_table('businesses')
    # ### end Alembic commands ###
