"""revamp to kyb table

Revision ID: 929fd0d4d221
Revises: 49e79d383f04
Create Date: 2026-07-04 22:30:21.086111+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '929fd0d4d221'
down_revision: Union[str, None] = '49e79d383f04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'cac_registration_number')
    op.drop_column('businesses', 'business_premises_photos')
    op.add_column('kyb_verifications', sa.Column('proof_of_address', sa.Text(), nullable=True))
    op.add_column('kyb_verifications', sa.Column('cac_registration_number', sa.String(length=20), nullable=True))
    op.add_column('kyb_verifications', sa.Column('business_premises_photos', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False))
    op.drop_index(op.f('idx_kyb_id_type'), table_name='kyb_verifications')
    op.drop_column('kyb_verifications', 'document_url')
    op.drop_column('kyb_verifications', 'id_type')
    op.drop_column('kyb_verifications', 'id_number')
    op.drop_column('kyb_verifications', 'rejection_reason')
    op.drop_column('kyb_verifications', 'provider_reference')
    op.drop_column('kyb_verifications', 'provider')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kyb_verifications', sa.Column('provider', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('kyb_verifications', sa.Column('provider_reference', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('kyb_verifications', sa.Column('rejection_reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('kyb_verifications', sa.Column('id_number', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('kyb_verifications', sa.Column('id_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('kyb_verifications', sa.Column('document_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_kyb_id_type'), 'kyb_verifications', ['id_type'], unique=False)
    op.drop_column('kyb_verifications', 'business_premises_photos')
    op.drop_column('kyb_verifications', 'cac_registration_number')
    op.drop_column('kyb_verifications', 'proof_of_address')
    op.add_column('businesses', sa.Column('business_premises_photos', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('businesses', sa.Column('cac_registration_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
