"""orders transactions order_items and order_status_events tables

Revision ID: 331cbd758356
Revises: 213b6f55906e
Create Date: 2026-07-06 09:29:18.311399+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '331cbd758356'
down_revision: Union[str, None] = '213b6f55906e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('reference_id', sa.String(length=50), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=True),
    sa.Column('channel', sa.Enum('online_booking', 'walk_in', 'subscription_fulfillment', name='channel_enum'), server_default='online_booking', nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('payment_status', sa.Enum('pending', 'paid', 'refunded', name='payment_status_enum'), server_default='pending', nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('customer_whatsapp', sa.String(length=30), nullable=True),
    sa.Column('to_be_delivered', sa.Boolean(), nullable=False),
    sa.Column('delivery_address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('scheduled_pickup_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('reference_id')
    )
    op.create_index('ix_orders_business_channel', 'orders', ['business_id', 'channel'], unique=False)
    op.create_index('ix_orders_business_date', 'orders', ['business_id', 'created_at'], unique=False)
    op.create_index('ix_orders_business_email', 'orders', ['business_id', 'customer_email'], unique=False)
    op.create_index('ix_orders_business_payment', 'orders', ['business_id', 'payment_status'], unique=False)
    op.create_index('ix_orders_business_status', 'orders', ['business_id', 'status'], unique=False)
    op.create_index('ix_orders_business_whatsapp', 'orders', ['business_id', 'customer_whatsapp'], unique=False)
    op.create_index('ix_orders_idempotency_key', 'orders', ['idempotency_key'], unique=False)
    op.create_index('ix_orders_reference_id', 'orders', ['reference_id'], unique=False)
    op.create_table('order_status_events',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_role', sa.String(length=20), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_order_status_events_order_time', 'order_status_events', ['order_id', 'timestamp'], unique=False)
    op.create_table('transactions',
    sa.Column('business_id', sa.UUID(), nullable=True),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('reference_id', sa.String(length=50), nullable=False),
    sa.Column('merchant_tx_ref', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=5), nullable=False),
    sa.Column('status', sa.Enum('pending', 'success', 'failed', 'refunded', name='transaction_status_enum'), server_default='pending', nullable=False),
    sa.Column('payment_channel', sa.String(length=30), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_tx_ref'),
    sa.UniqueConstraint('reference_id')
    )
    op.create_index('ix_transactions_business_date', 'transactions', ['business_id', 'created_at'], unique=False)
    op.create_index('ix_transactions_business_id', 'transactions', ['business_id'], unique=False)
    op.create_index('ix_transactions_merchant_tx_ref', 'transactions', ['merchant_tx_ref'], unique=False)
    op.create_index('ix_transactions_order_id', 'transactions', ['order_id'], unique=False)
    op.create_table('order_items',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('price_list_item_id', sa.UUID(), nullable=True),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('service_types', postgresql.ARRAY(sa.String(length=50)), server_default='{}', nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['price_list_item_id'], ['price_list_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_order_items_order_id', 'order_items', ['order_id'], unique=False)
    op.create_index('ix_order_items_price_list_item_id', 'order_items', ['price_list_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_order_items_price_list_item_id', table_name='order_items')
    op.drop_index('ix_order_items_order_id', table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('ix_transactions_order_id', table_name='transactions')
    op.drop_index('ix_transactions_merchant_tx_ref', table_name='transactions')
    op.drop_index('ix_transactions_business_id', table_name='transactions')
    op.drop_index('ix_transactions_business_date', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('ix_order_status_events_order_time', table_name='order_status_events')
    op.drop_table('order_status_events')
    op.drop_index('ix_orders_reference_id', table_name='orders')
    op.drop_index('ix_orders_idempotency_key', table_name='orders')
    op.drop_index('ix_orders_business_whatsapp', table_name='orders')
    op.drop_index('ix_orders_business_status', table_name='orders')
    op.drop_index('ix_orders_business_payment', table_name='orders')
    op.drop_index('ix_orders_business_email', table_name='orders')
    op.drop_index('ix_orders_business_date', table_name='orders')
    op.drop_index('ix_orders_business_channel', table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
