"""category price_list and subscription tables

Revision ID: 49e79d383f04
Revises: dcf25f055e40
Create Date: 2026-07-04 18:42:51.888777+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49e79d383f04'
down_revision: Union[str, None] = 'dcf25f055e40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_categories_business_id', 'categories', ['business_id'], unique=False)
    op.create_index('ix_categories_business_id_name', 'categories', ['business_id', 'name'], unique=True)
    op.create_table('subscription_plans',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('billing_cycle', sa.String(length=20), nullable=False),
    sa.Column('item_cap', sa.Integer(), nullable=False),
    sa.Column('eligible_category_ids', postgresql.ARRAY(sa.UUID()), server_default='{}', nullable=False),
    sa.Column('cancel_policy', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('plan_group_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_subscription_plans_eligible_categories', 'subscription_plans', ['eligible_category_ids'], unique=False, postgresql_using='gin')
    op.create_index('ix_subscription_plans_query_v2', 'subscription_plans', ['business_id', 'is_active', 'plan_group_id', 'version'], unique=False)
    op.create_table('price_list_items',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('service_types', postgresql.ARRAY(sa.String(length=50)), server_default='{}', nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('turnaround_hours', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_price_list_items_business_active', 'price_list_items', ['business_id', 'is_active'], unique=False)
    op.create_index('ix_price_list_items_category_id', 'price_list_items', ['category_id'], unique=False)
    op.create_index('ix_price_list_items_service_types', 'price_list_items', ['service_types'], unique=False, postgresql_using='gin')
    op.create_index('ix_businesses_city', 'businesses', ['city'], unique=False)
    op.create_index('ix_businesses_state', 'businesses', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_businesses_state', table_name='businesses')
    op.drop_index('ix_businesses_city', table_name='businesses')
    op.drop_index('ix_price_list_items_service_types', table_name='price_list_items', postgresql_using='gin')
    op.drop_index('ix_price_list_items_category_id', table_name='price_list_items')
    op.drop_index('ix_price_list_items_business_active', table_name='price_list_items')
    op.drop_table('price_list_items')
    op.drop_index('ix_subscription_plans_query_v2', table_name='subscription_plans')
    op.drop_index('ix_subscription_plans_eligible_categories', table_name='subscription_plans', postgresql_using='gin')
    op.drop_table('subscription_plans')
    op.drop_index('ix_categories_business_id_name', table_name='categories')
    op.drop_index('ix_categories_business_id', table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
